### PR TITLE
Upgrade to sbt 1.6.2 and git-plugin 2.0.0

### PR DESCRIPTION
**Pull request by gbastkowski**

### CODE REVIEW

**Comment by esgott** [comment]
This project looks pretty much abandoned, but if the maintainers notice this, there are a few users out there :)

**Comment by agemooij** [comment]
Apologies for the lack of updates everyone! I have to admit I've been very busy lately and the big barrier to accepting a quick update is that I'll need to find another place to publish this plugin since Bintray is no longer online. That inconvenient (mental, procrastination-inducing) barrier has left it lounging at the bottom of my todo list.

It's great to know I'm not the only user of this project so I'll try to free up some time for this. If anyone knows where I should publish OSS sbt plugins nowadays, please do let me know.

**Comment by gbastkowski** [comment]
> If anyone knows where I should publish OSS sbt plugins nowadays, please do let me know.

I just googled a little. Came up with two links that might be helpful:

- https://central.sonatype.org/publish/publish-guide/
- https://github.com/sbt/sbt-ci-release

I just skimmed the documents, but it looks pretty straight forward. Get an account for Sonatype and use some sbt plugin to automate the process.

**Comment by agemooij** [comment]
I've merged a newer Pr that updated the same dependencies to later versions.
I'll schedule some time this week to release and distribute a new binary version.

**Pull request closed without merging**
