### PR TITLE
Add a promptlet with current scala version

### PR DESCRIPTION
**Pull request by alonsodomin**
An additional promptlet to see what is the current scala version in the SBT prompt, as I find it quite useful when working on cross-compiled projects.

I also created a `Scalapenos2Theme` that includes that promptlet plus an example. Let me know if you are fine with that or if you'd like a better name for it.

### CODE REVIEW

**Comment by agemooij** [comment]
Nice new promptlet!

You are the first to contribute a new theme and for me that raises the question on how promptlets and themes are linked and whether we should provide a theme per unique combination of promptlets (answer: probably not). 

I think that in the long run it would make more sense to decouple the styling aspects of themes more strongly from the promptlet composition so I'll probably think on that for a bit.

Would you mind removing the new theme from this PR for now? If you do mind than I'm also ok with adding a theme for now as long as it is more explicitly named for what it provides.

Thanks again for your contribution and for being a user of this little plugin.

**Comment by alonsodomin** [comment]
Yeah, that makes total sense. I use a different theme anyway, a "minimal" version of https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#lambda (which I could PR separately if interested), so removing this "sample" theme does not bother me.

**Comment by agemooij** [comment]
Thanks! 

Could you perhaps also update the list of portlets in the README?

Feel free to also had your custom theme to the README as an example, perhaps in a **Theme examples* section at the bottom? A screenshot of the same shape as the one on top would also be cool.

**Comment by alonsodomin** [comment]
I added the new promptlet to the README. I didn't add my custom theme to the doc mostly because I'm sort of hacking the `GitInfo` class (using my own version), to be able to have a number of staged but not yet commited files. That's why I was thinking of probably submitting it as another PR, because it would mean "evolve" that case class to provide with more info. Let me know if that's something that sounds interesting to you.

Cheers.

**Comment by agemooij** [comment]
Thanks. Please go ahead and add a PR for more features in the `GitInfo` class if they are generally useful for building prompts. 

If, on the other hand, the specific information that you want to add is highly personal and you think there are probably not all that many people with the same wishes, then perhaps it might be better to make it easier to redesign the git parsing code for easier customization by users.

**Comment by agemooij** [comment]
I'll try to release a new version ASAP

**Pull request merged**
